/* Generated by Yosys 0.9+36 (git sha1 4aa505d1, clang 6.0.0-1ubuntu2 -fPIC -Os) */

(* \nmigen.hierarchy  = "top.failme" *)
(* generator = "nMigen" *)
module failme(rst);
  (* src = "assert_fail.py:18" *)
  wire \$2 ;
  (* src = "assert_fail.py:18" *)
  wire \$assume$check ;
  (* src = "assert_fail.py:18" *)
  wire \$assume$en ;
  (* src = "/home/robertbaruch/.local/lib/python3.6/site-packages/nmigen/hdl/ir.py:62" *)
  wire init;
  (* src = "assert_fail.py:37" *)
  input rst;
  \$initstate  \$1  (
    .Y(init)
  );
  assign \$2  = rst == (* src = "assert_fail.py:18" *) init;
  always @* if (\$assume$en ) assume(\$assume$check );
  assign \$assume$en  = 1'h1;
  assign \$assume$check  = \$2 ;
endmodule

(* \nmigen.hierarchy  = "top" *)
(* top =  1  *)
(* generator = "nMigen" *)
module top(rst, clk);
  (* src = "assert_fail.py:36" *)
  input clk;
  (* src = "assert_fail.py:37" *)
  input rst;
  failme failme (
    .rst(rst)
  );
endmodule

